database:
  host: localhost
  port: 5432
  username: dart
  password: dart
  databaseName: dart_test
registrationSecret: secret
cors:
  allowedOrigins:
    - http://localhost:8080
    - https://chrismeyers.info
    - https://www.chrismeyers.info
