name: api
description: The API powering chrismeyers.info
version: 0.0.1
author: Chris Meyers <chris@chrismeyers.info>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0+1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0

dependency_overrides:
  postgres: ^2.2.0
