name: API

on:
  push:
    paths:
      - .github/workflows/api.yml
      - packages/api/**
      - package-lock.json

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ci
      CORS_ALLOWED_ORIGINS: http://localhost:1337,http://localhost:1234

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/api/package.json

      - name: Install dependencies
        run: npm ci --workspace=api

      - name: Lint Code
        run: npm run lint --workspace=api

      - name: Run tests
        run: npm test --workspace=api
