name: API

on:
  push:
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/api.yml'
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ci
      CORS_ALLOWED_ORIGINS: http://localhost:1337,http://localhost:1234

    defaults:
      run:
        shell: bash
        working-directory: ./api

    container:
      image: node:16.3.0-slim

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run tests
        run: npm run test:ci
