name: API

on:
  push:
    paths:
      - .github/workflows/api.yml
      - packages/api/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/api.yml
      - packages/api/**

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ci
      CORS_ALLOWED_ORIGINS: http://localhost:1337,http://localhost:1234

    defaults:
      run:
        shell: bash

    container:
      image: node:16.10.0-slim

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn workspaces focus api

      - name: Lint Code
        run: yarn workspace api lint

      - name: Run tests
        run: yarn workspace api test:ci
