name: Web

on:
  push:
    paths:
      - .github/workflows/web.yml
      - packages/web/**
      - package-lock.json

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/web/package.json

      - name: Install dependencies
        run: npm ci --workspace=web

      - name: Lint Code
        run: npm run lint --workspace=web

      - name: Run tests
        run: npm test --workspace=web
