name: Web

on:
  push:
    paths:
      - '.github/workflows/web.yml'
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/web.yml'
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./web

    container:
      image: node:16.3.0-slim

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --non-interactive --no-progress

      - name: Lint Code
        run: yarn lint

      - name: Run tests
        run: yarn test:ci
