name: Web

on:
  push:
    branches: [ master ]
    paths:
      - 'web/src/**'
      - '!web/src/assets/**'
      - 'web/tests/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'web/src/**'
      - '!web/src/assets/**'
      - 'web/tests/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./web

    container:
      image: node:14.15.1

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
